### ISSUE TITLE
configuration for section wildlife is mishandling

### ISSUE THREAD

**Issue by dixudx** [dixudx/wildlife#4]
If only one cluster is needed, [wild.py](https://github.com/dixudx/wildlife/blob/069fc963e3ebbafff6de555cc6e70888b0498f8e/wildlife/wild.py#LC37) cannot well parse the below format.

``` yaml
wildlife: cluster01

clusters:
  - name: cluster01
    hosts: xx.xx.xx.xx:2181
    timeout: 10.0
    randomize_hosts: True
```

However, the current [wild.py](https://github.com/dixudx/wildlife/blob/069fc963e3ebbafff6de555cc6e70888b0498f8e/wildlife/wild.py#LC37) can only parse below formats.

``` yaml
wildlife: 
  - cluster01

clusters:
  - name: cluster01
    hosts: xx.xx.xx.xx:2181
    timeout: 10.0
    randomize_hosts: True
```
